"""Collects the raw claude CLI output from slo-post-experiment.sh into one JSON file.

Kept separate from the shell script so the shaping is readable. Reads its inputs
from the environment because the shell script already holds them.
"""
import json
import os
import pathlib
import datetime

work = pathlib.Path(os.environ["WORK"])
out = pathlib.Path(os.environ["OUT"])
questions = json.loads(os.environ["QUESTIONS_JSON"])


def load(name):
    return json.loads((work / name).read_text())


def parsed(raw):
    """The CLI returns the model's text in `result`; with --json-schema it is JSON."""
    try:
        return json.loads(raw["result"])
    except (json.JSONDecodeError, TypeError):
        return {"verdict": None, "reason": raw.get("result", "")}


cost = 0.0
items = []

for i, question in enumerate(questions):
    entry = {"id": i, "question": question, "answers": {}, "pairwise": {}}
    for v in ("a", "b"):
        ans = load(f"ans-{i}-{v}.json")
        grade = load(f"grade-{i}-{v}.json")
        cost += ans["total_cost_usd"] + grade["total_cost_usd"]
        entry["answers"][v] = {
            "text": ans["result"],
            "judge": parsed(grade),
        }
    for order in ("ab", "ba"):
        pair = load(f"pair-{i}-{order}.json")
        cost += pair["total_cost_usd"]
        picked = parsed(pair)
        # Normalise position ("first"/"second") to identity ("a"/"b") so a flip
        # between the two orders is visible without re-deriving the mapping.
        if order == "ab":
            picked["picked"] = "a" if picked.get("winner") == "first" else "b"
        else:
            picked["picked"] = "b" if picked.get("winner") == "first" else "a"
        entry["pairwise"][order] = picked
    entry["position_flip"] = entry["pairwise"]["ab"]["picked"] != entry["pairwise"]["ba"]["picked"]
    items.append(entry)

out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(
    json.dumps(
        {
            "generated": datetime.date.today().isoformat(),
            "answerer": os.environ["ANSWERER"],
            "judge": os.environ["JUDGE"],
            "total_cost_usd": round(cost, 4),
            "note": (
                "Answers were generated with no runbooks, no retrieval, and no cluster "
                "access. The judge saw the question and the answer, never a reference "
                "answer. Generated by scripts/slo-post-experiment.sh."
            ),
            "items": items,
        },
        indent=2,
    )
    + "\n"
)

flips = sum(1 for e in items if e["position_flip"])
fails = sum(1 for e in items for v in e["answers"].values() if v["judge"].get("verdict") == "fail")
print(f"wrote {out}")
print(f"  judge failed {fails}/{len(items) * 2} answers")
print(f"  position flipped on {flips}/{len(items)} questions")
print(f"  cost ${cost:.4f}")
